### ISSUE TITLE
Running deep-tempest in RF Swift

### ISSUE THREAD

**Issue by bar-mm** [PentHertz/RF-Swift#14]
Tell me how to install and run deeptempest in RF Swift (https://x.com/FlUxIuS/status/1814200363718697210)?

**Comment by FlUxIuS** [comment]
Hi,

More politeness would be appreciated.

Is that an issue? Or is this a question?

If it's a question, can you describe your problem. If it is an issue, you can ask questions on the chat.

Anyway, you can also look at https://rfswift.io/docs/quick-start/ to see how to run RF Swift and download the `deeptempest` image to run.

Thank you.

Cheers,

**Comment by bar-mm** [comment]
Hello.
Thanks for the quick response.
The question was about the specifics of running deeptempest in RF Swift.
I downloaded the deeptempest image.
Create and run a container.

![Image](https://github.com/user-attachments/assets/20d05f12-3c23-4b57-a2c1-a65ef39d307e)

I wanted to run GNU from the container and open deep-tempest_example.grc in it.
Running GNU gave the following errors.

![Image](https://github.com/user-attachments/assets/43479ed8-7f64-4bc0-8053-81f2b0fb50da)

![Image](https://github.com/user-attachments/assets/e3d13ea4-f405-47b9-b66f-d6efb6c4dde0)

Thank you.
Cheers.

**Comment by FlUxIuS** [comment]
Hey,
There is an issue with Numpy version installed by the deeptempest repo now. You can quickly fix it with : 
`pip3 install "numpy<2.0"`

**Comment by bar-mm** [comment]
Hello.
Thanks for the quick response.
GNU Radio started!
Project deep-tempest_example.grc opened from /rftools/sdr/oot/deep-tempest/gr-tempest/examples/
When starting, an error appears:
```
Traceback (most recent call last):
  File "/rftools/sdr/oot/deep-tempest/gr-tempest/examples/manual_tempest_example.py", line 48, in <module>
    import tempest
ModuleNotFoundError: No module named 'tempest'
```

![Image](https://github.com/user-attachments/assets/394b6602-16a4-490d-bbb8-e6a9c57576dd)
Thank you.

**Comment by FlUxIuS** [comment]
Hey,

As a quick fix you can create this symbolic link: `ln -s /usr/local/lib/python3.10/dist-packages/gnuradio/tempest /usr/lib/python3.10/tempest`

We will create another image for that one late fixing all issues.

**Comment by bar-mm** [comment]
Thank you.
The error "No module named 'tempest'" has been fixed.
New errors have appeared.
The only thing I checked was on manual_simulated_tempest_example.grc:

Generating: '/rftools/sdr/oot/deep-tempest/gr-tempest/examples/simulations/manual_simulated_tempest_example.py'
Executing: /usr/bin/python3 -u /rftools/sdr/oot/deep-tempest/gr-tempest/examples/simulations/manual_simulated_tempest_example.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "/rftools/sdr/oot/deep-tempest/gr-tempest/examples/simulations/manual_simulated_tempest_example.py", line 413, in <module>     main()
  File "/rftools/sdr/oot/deep-tempest/gr-tempest/examples/simulations/manual_simulated_tempest_example.py", line 391, in main
    tb = top_block_cls()
  File "/rftools/sdr/oot/deep-tempest/gr-tempest/examples/simulations/manual_simulated_tempest_example.py", line 180, in __init__
    self.tempest_image_source_0 = tempest.image_source('/rftools/sdr/oot/deep-tempest/gr-tempest/Imagen_800_600.png', 800, 600, 1024, 624, 1)
AttributeError: module 'tempest' has no attribute 'image_source'
>>> Done (return code 1)

I'll check later  deep-tempest_example.grc
Thanks

**Comment by FlUxIuS** [comment]
With this one only you can help yourself as you need to provide valid arguments in your flowgraph

**Comment by FlUxIuS** [comment]
Hello,

Issues got fixed with a new "deeptempest" available now. 

I'm closing this issue ;)

**Comment by bar-mm** [comment]
Hello.
Thanks for the answers.
The problem remains in the deep-tempest_example.grc module.
And it is not related to the arguments in the scheme.

Generating: '/rftools/sdr/oot/deep-tempest/gr-tempest/examples/manual_tempest_example.py'
Executing: /usr/bin/python3 -u /rftools/sdr/oot/deep-tempest/gr-tempest/examples/manual_tempest_example.py
Error: failed to enable real-time scheduling.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "/rftools/sdr/oot/deep-tempest/gr-tempest/examples/manual_tempest_example.py", line 526, in <module>
    main()
  File "/rftools/sdr/oot/deep-tempest/gr-tempest/examples/manual_tempest_example.py", line 504, in main
    tb = top_block_cls()
  File "/rftools/sdr/oot/deep-tempest/gr-tempest/examples/manual_tempest_example.py", line 166, in __init__
    self.tempest_tempest_msgbtn_0 = _tempest_tempest_msgbtn_0_toggle_button = tempest.tempest_msgbtn('Adjust image (sampling ratio finder). ', 'pressed',True,"default","default")
AttributeError: module 'tempest' has no attribute 'tempest_msgbtn'. Did you mean: 'tempest_python'?
 Done (return code 1)

Thanks
